version: '3'

services:
        web:
                build: .
                container_name: "my-web-php7.0"
                ports:
                - "8000:80"
                volumes:
                - .:/code
#                - logvolume01:/var/log
        db:
                image: mysql:5.7
                environment:
                        MYSQL_ROOT_PASSWORD: my_secret_pw_shh
                        MYSQL_DATABASE: test_db
                        MYSQL_USER: devuser
                        MYSQL_PASSWORD: devpass
                ports:
                        - "9906:3306"
#        volumes:
#                logvolume01: {}